---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: bitwarden
  labels:
    app: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      serviceAccountName: bitwarden
      securityContext:
        fsGroup: 33
        runAsUser: 33
      containers:
      - image: bitwardenrs/server:1.19.0-alpine
        imagePullPolicy: IfNotPresent
        name: bitwarden
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: domain-fqdn
        - name: DATA_FOLDER
          value: /data
        - name: ROCKET_WORKERS
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: rocket-workers
        - name: ROCKET_PORT
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: rocket-port
        - name: SHOW_PASSWORD_HINT
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: password-hint
        - name: SMTP_FROM
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: smtp-from
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: smtp-server
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: smtp-port
        - name: SMTP_SSL
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: smtp-ssl
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitwarden-smtp
              key: smtp_password
        - name: WEBSOCKET_ENABLED
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: websocket
        - name: WEB_VAULT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: bitwarden
              key: web-vault
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 3012
          name: websocket
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "15Gi"
      storageClassName: default