
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  name: bitwarden-mysql-config
  labels:
    app: bitwarden
data:
  mysql.password: 'ohpaek6ohM'
  mysql.user: 'db-user'
  mysql.root-password: 'LuaQuahb8u!'
  my.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8

    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    skip-log-bin
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    # Recommended in standard MySQL setup
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    # This increase of max_connections from the default of 151 to 1024 has been
    # tested as adequate for an environment with up to 24 API/Worker/Collector
    # components (8 of each) and 4000 Agents of incoming traffic. The MySQL
    # container also consumed as much as 1 GB of memory in this test.
    max_connections=1024
    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: bitwarden-mysql
  labels:
    app: bitwarden
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: bitwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  name: bitwarden-mysql
  labels:
    app: bitwarden
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
  serviceName: bitwarden-mysql-cluster
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      initContainers:
        - name: mysql-init
          image: mysql:5.7
          resources: {}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - chown
            - 999:999
            - /var/lib/mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          securityContext:
            runAsUser: 999
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bitwarden-mysql-config
                  key: mysql.root-password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: bitwarden-mysql-config
                  key: mysql.user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bitwarden-mysql-config
                  key: mysql.password
            - name: MYSQL_DATABASE
              value: bitwarden       
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: data
              mountPath: /var/lib/mysql
      securityContext: {}
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      volumes:
        - name: mysql-config
          configMap:
            defaultMode: 420
            name: bitwarden-mysql-config
