---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-config
  labels:
    app: bitwarden
data:
  #config.json: |
  ## Bitwarden_RS/vaultwarden Configuration File
  ## Additional options can be found at https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
  SMTP_HOST: 'smtp.domain.tld'
  SMTP_FROM: 'user@smtp.domain.tld'
  SMTP_FROM_NAME: 'Bitwarden_RS'
  SMTP_PORT: '587'
  SMTP_SSL: 'true'
  SMTP_USERNAME: 'user@smtp.domain.tld'
  SMTP_PASSWORD: 'password'
  ## Enables websocket notifications
  WEBSOCKET_ENABLED: 'true'
  ## Domain settings
  DOMAIN: 'https://bitwarden.domain.tld'
  ## Rocket specific settings, check Rocket documentation to learn more
  ROCKET_PORT: '8080'
  # ROCKET_TLS: {certs: '/path/to/certs.pem',key: '/path/to/key.pem'}
      
  ## Whether password hint should be sent into the error response when the client request it
  SHOW_PASSWORD_HINT: 'false'
  
  ## Web vault settings
  WEB_VAULT_ENABLED: 'true'
  ## Main data folder
  DATA_FOLDER: '/data'
  
  ## Database URL and Database max connections
  # DATABASE_URL=postgresql://user:password@host[:port]/database_name
  #DATABASE_URL: postgresql://user:password@bitwarden-postgresql/database_name
  DATABASE_URL: 'postgresql://db-user:ohpaek6ohM@bitwarden-postgresql/bitwarden'
  DATABASE_MAX_CONNS: '10'
  ## Number of times to retry the database connection during startup, with 1 second delay between each retry, set to 0 to retry indefinitely
  # DB_CONNECTION_RETRIES: 15

  ## Client IP Header, used to identify the IP of the client, defaults to 'X-Client-IP'
  ## Set to the string 'none' (without quotes), to disable any headers and just use the remote IP
  # IP_HEADER: X-Client-IP
  
  ## Log level
  ## Valid values are 'trace', 'debug', 'info', 'warn', 'error' and 'off'
  # LOG_LEVEL: Info    
      
  ## HIBP Api Key
  ## HaveIBeenPwned API Key, request it here: https://haveibeenpwned.com/API/Key
  # HIBP_API_KEY: 
